services:
  # PHP-FPM сервис
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.3-fpm  # или php:8.4-fpm, когда будет доступен
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  # Nginx сервис
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  # MySQL сервис
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

# Определение томов и сетей
volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge